Выполнил часть ДЗ
htmlacademy-htmlcss/1496867-nerds-29 pull request #2
Opened 2020-09-16 17:21 UTC by AyBalatsan

Прошу проверить и дать рекомендации по замечаниям.

2020-09-17 07:29 UTC, andreysgra requested changes
1. В задании написано:

![image](https://user-images.githubusercontent.com/17790771/93432439-34bd6400-f8ce-11ea-866b-0d528359a50f.png)

Все файлы графики уберите, в html замените на заглушки. Задание по графике будет только после четвёртой лекции.

2. Есть ошибки валидации HTML. Проверить можно [здесь](https://validator.w3.org/nu/#textarea).

3. Не вижу в разметке этого блока:

![image](https://user-images.githubusercontent.com/17790771/93433709-d5f8ea00-f8cf-11ea-8566-898ab2e223ac.png)

2020-09-17 07:29 UTC, andreysgra commented on index.html
> +			<a href="index.html">
```suggestion
			<a>
```
так как страница не должна на себя ссылаться.

2020-09-17 07:29 UTC, andreysgra commented on index.html
> +				<li><a href="Clients.html">Клиенты</a></li>
К чему заглавные буквы в `href`? Ссылки, как правило, пишутся прописными буквами.

2020-09-17 07:29 UTC, andreysgra commented on index.html
> +				<li><a href="Contacts.html">Контакты</a></li>
Аналогично предыдущему комментарию.

2020-09-17 07:29 UTC, andreysgra commented on index.html
> +				<a href="blank.html">Вход</a>
Не вижу такой ссылки в этом проекте. Есть "корзина".

2020-09-17 07:29 UTC, andreysgra commented on index.html
> +		</section>
Это всё один слайд:

![image](https://user-images.githubusercontent.com/17790771/93433324-53702a80-f8cf-11ea-964f-44488f9f049e.png)

Не нужно разделять его на отдельные блоки.

2020-09-17 07:29 UTC, andreysgra commented on index.html
> +					<button type="button">Заказать</button>
Это ссылка.

2020-09-17 07:29 UTC, andreysgra commented on index.html
> +					<h3>презинтации</h3>
```suggestion
					<h3>Презентации</h3>
```

2020-09-17 07:29 UTC, andreysgra commented on index.html
> +			<button  type="button">Напишите нам</button>
Ссылка.

2020-09-17 07:29 UTC, andreysgra commented on index.html
> +			<p>191186, Санкт-Петербург,<br> ул. Б. Конюшенная, д. 19/8<br> тел. +7 (812) 275 75 75</p>
Телефон размечается ссылкой с протоколом `tel` (критерий [Д29](https://up.htmlacademy.ru/htmlcss/29/criteries#d29)).

2020-09-17 07:29 UTC, andreysgra commented on index.html
> +	</section>
Блок карты нужно разместить в футере, перед блоком "Социальные сети". В этом блоке никакой кнопки в макете нет.

2020-09-17 07:29 UTC, andreysgra commented on index.html
> +			<h2>Давайте дружить</h2>
Ну этот заголовок лишний.

2020-09-17 07:29 UTC, andreysgra commented on index.html
> +			<h3>NЁRDS DESIGN STUDIO</h3>
Это просто параграф.

2020-09-17 17:17 UTC, andreysgra requested changes

2020-09-17 17:17 UTC, andreysgra commented on index.html
> +				<a href="blank.html"><img src="https://via.placeholder.com/150x100" alt=""></a>
Эта картинка с изображением корзины относится к ссылке "корзина" и её не нужно размечать отдельной ссылкой. Иконка является декоративным изображением и ей не нужен тег `img` (потом мы добавим её средствами CSS).

2020-09-17 17:17 UTC, andreysgra commented on index.html
> +					<button type="button">Заказать</button>
Это ссылка (тег `<a>`). (И тоже самое в других блоках раздела "услуги").

2020-09-17 17:17 UTC, andreysgra commented on index.html
> +					<h3>Презинтации</h3>
```suggestion
					<h3>Презентации</h3>
```

Текст лучше копировать из макета, так меньше вероятность допустить орфографические ошибки (но бывают и в макетах ошибки 😏 ).

2020-09-17 17:17 UTC, andreysgra commented on index.html
> +			<button  type="button">Напишите нам</button>
Это ссылка (тег `<a>`).

2020-09-17 17:17 UTC, andreysgra commented on index.html
> +			<h3>Мы - маленькая, но гордая<br>дизайн-студия из Краснодара.</h3>
Данный текст мало похож на заголовок. Лучше заменить на параграф.

2020-09-20 17:26 UTC, AyBalatsan commented on index.html
> +			<button  type="button">Напишите нам</button>
Не понял, что должно быть в ссылке

2020-09-20 18:06 UTC, andreysgra commented on index.html
> +			<button  type="button">Напишите нам</button>
У вас этот элемент размечен кнопкой: `<button  type="button">Напишите нам</button>`, а это должна быть ссылка: `<a href="#">Напишите нам</a>`

2020-09-21 15:03 UTC, andreysgra approved these changes

2020-09-21 15:03 UTC, andreysgra commented on index.html
> +				</li>
Вы меня неверно поняли в прошлый раз. Комментарий "это ссылка" относился к кнопке "заказать", а не к изображению. В этом блоке разметка должна быть такой:
```suggestion
				<li>
					<img src="https://via.placeholder.com/150x100" alt="">
					<h3>Веб-сайты</h3>
					<a href="#">Заказать</a>
				</li>
```
(соответственно в двух других блоках, тоже).

2020-09-21 15:03 UTC, merged