Сетка на гридах для главной страницы
htmlacademy-htmlcss/1496867-nerds-29 pull request #7
Opened 2020-10-06 13:55 UTC by AyBalatsan

2020-10-06 17:15 UTC, andreysgra requested changes
Можно (и лучше) создать отдельный класс `.container` в который вынести свойства центровщика:
```
  width: 1160px;
  margin: 0 auto;
  padding: 0 20px;
```
и использовать этот класс там, где требуется центрировать контент. Для сравнения: у вас для этой цели использованы разные классы - `.center`, `.main-navigation-wrapper` (в этом классе есть данные свойства).

2020-10-06 17:15 UTC, andreysgra commented on css/style.css
> +	grid-template-columns: 3fr 9fr 3fr;
Здесь можно шаблон упростить: разделим все значения на общий множитель 3 и получим такие значения `1fr 3fr 1fr`.

2020-10-06 17:15 UTC, andreysgra commented on css/style.css
> +	grid-template-columns: 1fr 1fr 1fr;
При таком шаблоне получается ширина одной колонки 320px

![image](https://user-images.githubusercontent.com/17790771/95232639-75ddcf80-080d-11eb-9f6e-bb1e46cc06fe.png)

а в макете оно составляет 300px. Происходит потому, что **1fr** относительная единица измерения, а справа от последнего блока есть свободное пространство 60px. Тут либо нужно задать в шаблоне размеры колонок в пикселах, либо (используя **fr**) добавить последнему блоку отступ справа.

2020-10-06 17:15 UTC, andreysgra commented on css/style.css
> +	grid-template-columns: 8fr 4fr;
Здесь тоже можно упростить шаблон - делим на 4 и получаем `2fr 1fr`.

2020-10-06 17:15 UTC, andreysgra commented on css/style.css
> +	grid-template-columns: 4fr 8fr;
Здесь тоже можно упростить шаблон - делим на 4 и получаем `2fr 1fr`.

2020-10-06 17:15 UTC, andreysgra commented on css/style.css
> +}
Здесь варианты могут быть разными:
1. Абсолютное позиционирование (пока не нужно делать, так как позиционирование вы не проходили).
2. Можно использовать grid. Он позволяет накладывать одни блоки на другие. Более подробно можно прочитать в [этой главе](https://up.htmlacademy.ru/htmlcss/29/book/6.2.4) учебника.

2020-10-07 14:50 UTC, AyBalatsan commented on css/style.css
> +}
Я знаю как наложить 2 объекта, но я не понимаю как его зафиксировать при расширении экрана? Когда начинаешь заужать или увеличивать окно браузера. Как поставить его по сетке, чтобы он позиционировался по первой линии

2020-10-07 19:07 UTC, andreysgra commented on css/style.css
> +}
Давайте пока не будем заниматься позиционированием этого блока :-)

2020-10-10 16:10 UTC, andreysgra approved these changes

2020-10-10 16:10 UTC, andreysgra commented on index.html
> +			<div class="inform-contacts center">
Класс `center` у этого блока нужно убрать, а сам блок обернуть в `div` с классом `center`:
```
<div class="center">
  <div class="inform-contacts">
	<p class="сompany-name">NЁRDS DESIGN STUDIO</p>
	<p class="company-address">191186, Санкт-Петербург, ул. Б. Конюшенная, д. 19/8 тел.<a class="footer-phone" href="tel:+78132757575">+7 (812) 275 75 75</a></p>
	<a class="button" href="#">Напишите нам</a>
  </div>
</div>
```

2020-10-10 16:10 UTC, merged